[package]
name = "nosedive"
version = "0.1.0"
edition = "2024"
default-run = "nosedive"

[dependencies]
dotenvy = "0.15.7"
serenity = "0.12.5"
tokio = { version = "1.49.0", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "macros" ] }

